### ISSUE TITLE
Fails under docker. Most likely to fail under different distros.

### ISSUE THREAD

**Issue by thesayyn** [jbedard/html-insert-assets#10]
I have been trying to understand why this package was not working. I have been getting an error when I put a statement into my docker file like this;

`RUN html-insert-assets --out index.html --assets switch.css switch.js --verbose`

 It was giving an error; 

`/usr/local/bin/html-insert-assets: 1: /usr/local/bin/html-insert-assets: //: Permission denied
/usr/local/bin/html-insert-assets: 3: /usr/local/bin/html-insert-assets: Syntax error: "(" unexpected
`

Turns out that the bin was pointed out to be src/main.js which does not include a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) statement to tell how to interpret this binary which is the main reason for the error.

**Comment by jbedard** [comment]
I've added a `bin` entry to package.json. Let me know if you're still having any issues.
