### ISSUE TITLE
Support for Manifests

### ISSUE THREAD

**Issue by flolu** [jbedard/html-insert-assets#17]
I would like to use this package for a PWA.
Thus a `--manifest` argument would be really handy.

**Example**
```
--manifest manifest.webmanifest
```

should result in

```
<link rel="manifest" href="manifest.webmanifest" />
```

**Comment by jbedard** [comment]
@flolu that sounds reasonable and easy to add.

Looks like there are no interesting attributes on the `<link>` for PWA manifests? So I think the API + result in your example is probably all that's needed?

**Comment by flolu** [comment]
@jbedard Yes you're right. That's all :)

**Comment by jbedard** [comment]
@flolu I've added exactly what you suggested.

I was debating just adding a generic `--link` to add any type of `<link>` in the world. That would be more then enough, and would cover some existing and future cases. However it would often require a lot of extra args to customize all the `<link>` attributes. I guess your use case is actually super simple and `--link` wouldn't be bad, but 🤷 

Let me know if you have any opinions on that, feedback (and feature requests!) is always good 👍

**Comment by flolu** [comment]
I've actually thought about that, too when writing the issue. But I couldn't really think of any other use cases (yet :laughing: )
So I guess `--manifest` is perfect for now.

And thank you so much for implementing the feature that fast!!!
