### ISSUE TITLE
make the leading slash configurable

### ISSUE THREAD

**Issue by funnyfrish** [jbedard/html-insert-assets#2]
when a base href is used than the injected js + asset file paths wont work. It always tries to
go to the main domain instead off the subfolder where the app is running

example:
domain.com/shop/app -> the injected paths with leading slash will show to domain.com/xxx.js instead of domain.com/shop/app/xxx.js.

**Comment by jbedard** [comment]
I thought this might be an issue. I think we can change `/` to always be `./`, so it will always be relative to the html file. Is that what you're thinking?

**Comment by jbedard** [comment]
@funnyfrish I think I've addressed this. Previously the roots only trimmed the paths, and all paths were then assumed to be absolute. Now any paths where a root is not found are relative and navigate to the `--out` file (which might be in a root and get trimmed itself...).

It gets a little odd when a mix of absolute and relative paths start being used. Mixing URLs vs local paths :/

Please let me know how it goes. Might still be more to do here...
