### ISSUE TITLE
Add support for Preloading requests

### ISSUE THREAD

**Issue by flolu** [jbedard/html-insert-assets#7]
# Feature request
Page load times can be decreased by preloading links: https://web.dev/uses-rel-preload/

Which can be added to the head of a document:
```
<head>
  ...
  <link rel="preload" href="styles.css" as="style">
  <link rel="preload" href="ui.js" as="script">
  ...
</head>
```
Would be cool to see something like this:
```
html-insert-assets
    --preload my.js my.css
```

**Comment by flolu** [comment]
Awesome! I will try it later and report if there are any issues :muscle:

**Comment by jbedard** [comment]
Let me know how it goes, and any other bugs or ideas. Thanks! 🤔

**Comment by flolu** [comment]
I've just tried it and it seems to work fine for me, thank you! :smile:
