### ISSUE TITLE
`async` is resolved as `async=""`

### ISSUE THREAD

**Issue by flolu** [jbedard/html-insert-assets#9]
In the head of my html I have a link to a font like this
```html
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" async />
```
But after running `html-insert-assets` I get this as an output:
```html
<link href="https://fonts.googleapis.com/css2?family=Roboto&amp;display=swap" rel="stylesheet" async="">
```

Not the difference of `async`. It is now `async=""`. But it should just be `async`

**Comment by jbedard** [comment]
Interesting. It would be `parse5` doing that. I'll have to see if there's a way to disable that or maybe it's a bug (or "feature") of `parse5`...

**Comment by flolu** [comment]
Ok. As it seems `async` is interpreted exactly the same as `async=""`: https://github.com/inikulin/parse5/issues/184#issuecomment-286612352

So this shouldn't cause issues?!

**Comment by jbedard** [comment]
I think this is really just a style issue and makes no functional difference. An attribute with no value is equivalent to an empty string value. I do agree it would be nice if `prase5` provided style options to do on or the other, and leaving parsed attributes as-is. But I think I'll close this for now. If you think it's worth the effort let me know if you find an alternative or see a change (or find an existing feature) in `parse5` to allow this.

For reference:
https://github.com/inikulin/parse5/issues/184#issuecomment-286612352
https://github.com/inikulin/parse5/issues/177#issuecomment-278273728

**Comment by TokugawaTakeshi** [comment]
The empty string attribute value makes HTML invalid, e. g.:

```
Bad value “” for attribute “aria-pressed” on element “button”.
Bad value “” for attribute “aria-disabled” on element “a”.
```

**Comment by jbedard** [comment]
For those aria attributes blank is probably invalid, but I think for `async` the valid value is an empty string. Either way unfortunately this is a `parse5` issue that I don't think is worth working around for the same reasons they aren't fixing it.
